//API
export const API_CALL_BEGAN = "API_CALL_BEGAN"
export const API_CALL_SUCCESS = "API_CALL_SUCCESS"
export const API_CALL_FAILED = "API_CALL_FAILED"

//productType types
export const ADD_PRODUCT_TYPE = "ADD_PRODUCT_TYPE";
export const DELETE_PRODUCT_TYPE = "DELETE_PRODUCT_TYPE";
export const CLEAR_PRODUCT_TYPE = "CLEAR_PRODUCT_TYPE";
export const PRODUCT_TYPE_ERROR = "PRODUCT_TYPE_ERROR";
export const PRODUCT_TYPE_LOADED = "PRODUCT_TYPE_LOADED";
export const PRODUCT_TYPE_LOADING = "PRODUCT_TYPE_LOADING";

//inventory
export const ADD_INVENTORY = "ADD_INVENTORY";
export const DELETE_INVENTORY = "DELETE_INVENTORY";
export const CLEAR_INVENTORY = "CLEAR_INVENTORY";
export const INVENTORY_ERROR = "INVENTORY_ERROR";
export const INVENTORY_LOADED = "INVENTORY_LOADED";
export const INVENTORY_LOADING = "INVENTORY_LOADING";

//provider
export const ADD_PROVIDER = "ADD_PROVIDER";
export const DELETE_PROVIDER = "DELETE_PROVIDER";
export const CLEAR_PROVIDER = "CLEAR_PROVIDER";
export const PROVIDER_ERROR = "PROVIDER_ERROR";
export const PROVIDER_LOADED = "PROVIDER_LOADED";
export const PROVIDER_LOADING = "PROVIDER_LOADING";

//size 
export const ADD_SIZE = "ADD_SIZE";
export const DELETE_SIZE = "DELETE_SIZE";
export const CLEAR_SIZE = "CLEAR_SIZE";
export const SIZE_ERROR = "SIZE_ERROR";
export const SIZE_LOADED = "SIZE_LOADED";
export const SIZE_LOADING = "SIZE_LOADING";

//manufacturer
export const ADD_MANUFACTURER = "ADD_MANUFACTURER";
export const DELETE_MANUFACTURER = "DELETE_MANUFACTURER";
export const CLEAR_MANUFACTURER = "CLEAR_MANUFACTURER";
export const MANUFACTURER_ERROR = "MANUFACTURER_ERROR";
export const MANUFACTURER_LOADED = "MANUFACTURER_LOADED";
export const MANUFACTURER_LOADING = "MANUFACTURER_LOADING";

//users
export const ADD_USERS = "ADD_USERS";
export const DELETE_USERS = "DELETE_USERS";
export const CLEAR_USERS = "CLEAR_USERS";
export const USERS_ERROR = "USERS_ERRORS";
export const USERS_LOADED = "USERS_LOADED";
export const USERS_LOADING = "USERS_LOADING";

//items
export const ADD_ITEMS = "ADD_ITEMS";
export const UPDATE_ITEMS = "UPDATE_ITEMS";
export const DELETE_ITEMS = "DELETE_ITEMS";
export const CLEAR_ITEMS = "CLEAR_ITEMS";
export const ITEMS_ERROR = "ITEMS_ERRORS";
export const ITEMS_LOADED = "ITEMS_LOADED";
export const ITEMS_LOADING = "ITEMS_LOADING";

// incomingPurchase
export const ADD_INCOMING_PURCHASES = "ADD_INCOMING_PURCHASES";
export const DELETE_INCOMING_PURCHASES  = "DELETE_INCOMING_PURCHASES";
export const CLEAR_INCOMING_PURCHASES  = "CLEAR_INCOMING_PURCHASES";
export const INCOMING_PURCHASES_ERROR = "INCOMING_PURCHASES_ERRORS";
export const INCOMING_PURCHASES_LOADED = "INCOMING_PURCHASES_LOADED";
export const INCOMING_PURCHASES_LOADING = "INCOMING_PURCHASES_LOADING";

// incomingPurchaseDetails
export const ADD_INCOMING_PURCHASES_DETAILS = "ADD_INCOMING_PURCHASES_DETAILS";
export const UPDATE_INCOMING_PURCHASES_DETAILS = "UPDATE_INCOMING_PURCHASES_DETAILS";
export const DELETE_INCOMING_PURCHASES_DETAILS  = "DELETE_INCOMING_PURCHASES_DETAILS ";
export const CLEAR_INCOMING_PURCHASES_DETAILS   = "CLEAR_INCOMING_PURCHASES_DETAILS ";
export const INCOMING_PURCHASES_DETAILS_ERROR = "INCOMING_PURCHASES_DETAILS_ERRORS";
export const INCOMING_PURCHASES_DETAILS_LOADED = "INCOMING_PURCHASES_DETAILS_LOADED";
export const INCOMING_PURCHASES_DETAILS_LOADING = "INCOMING_PURCHASES_DETAILS_LOADING";

// inventoryItem

export const ADD_INVENTORYITEM = " ADD_INVENTORITEM";
export const DELETE_INVENTORYITEM = "DELETE_INVENTORITEM";
export const CLEAR_INVENTORYITEM = "CLEAR_INVENTORITEM";
export const INVENTORYITEM_ERROR = "INVENTORITEM_ERROR";
export const INVENTORYITEM_LOADED = "INVENTORITEM_LOADED";
export const INVENTORYITEM_LOADING = "INVENTORITEM_LOADING";
export const UPDATE_INVENTORYITEM = "UPDATE_INVENTORYITEM"

// stock

// export const ADD_INVENTORYITEM = " ADD_INVENTORITEM";
// export const DELETE_INVENTORYITEM = "DELETE_INVENTORITEM";
// export const CLEAR_INVENTORYITEM = "CLEAR_INVENTORITEM";
export const STOCK_ERROR = "STOCK_ERROR";
export const STOCK_LOADED = "STOCK_LOADED";
export const STOCK_LOADING = "STOCK_LOADING";
export const STOCKBYINVENTORY_LOADED = 'STOCKBYINVENTORY_LOADED'
// export const UPDATE_INVENTORYITEM = "UPDATE_INVENTORYITEM"


// inventoryItem

export const ADD_COMPANIES = " ADD_COMPANIES";
export const DELETE_COMPANIES= "DELETE_COMPANIES";
export const CLEAR_COMPANIES = "CLEAR_COMPANIES";
export const COMPANIES_ERROR = "COMPANIES_ERROR";
export const COMPANIES_LOADED = "COMPANIES_LOADED";
export const COMPANIES_LOADING = "COMPANIES_LOADING";